[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kaktus-logger"
dynamic = ["version"]
description = "Logger with extensive settings"
readme = "readme.md"

license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "3elenyi Kaktus"}
]
maintainers = []
keywords = ["logger"]
classifiers = []

requires-python = ">=3.10"
dependencies = [
    "kaktus-json-helpers>=4.0.2",
    "loguru>=0.7.3",
]

import-namespace = ["kaktus"]
import-names = ["kaktus.logger"]

[dependency-groups]
build = [
    "build>=1.5.0",
    "twine>=7.0.0",
]
dev = [
    "mypy>=2.3.0",
    "poethepoet>=0.48.0",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]


[project.urls]
Repository = "https://github.com/3elenyi-Kaktus/logger"


[tool.hatch.version]
path = "src/kaktus/logger/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/kaktus"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "ASYNC", # flake8-async
]
ignore = [
    "E501", # already handled by ruff formatter
]

[tool.ruff.lint.isort]
lines-after-imports = 2
combine-as-imports = true
force-sort-within-sections = true

[tool.mypy]
explicit_package_bases = true
mypy_path = "src"
strict = true

[tool.poe.tasks]
# Formatting, Linting, Typechecking
fmt-imports = "uv run ruff check --select I --fix"
fmt-base = "uv run ruff format"
fmt = ["fmt-imports", "fmt-base"]
lint = "uv run ruff check"
type = "uv run mypy"

# Tests
test = "uv run pytest -v"

# Build & Distribution
build = "uv run python -m build"
upload-test = "uv run python -m twine upload --repository testpypi dist/*"
upload = "uv run python -m twine upload dist/*"

# Combined runner
all = ["fmt", "lint", "type", "test", "build"]
